// DTLS 1.2 state machine types and security parameters

import * as crypto from 'node:crypto';

export enum DtlsState {
  New = 'new',
  Connecting = 'connecting',
  Connected = 'connected',
  Closed = 'closed',
  Failed = 'failed',
}

export interface SecurityParameters {
  entity: 'client' | 'server';
  cipherSuite: number;
  masterSecret: Buffer;
  clientRandom: Buffer;
  serverRandom: Buffer;
  clientWriteKey: Buffer;
  serverWriteKey: Buffer;
  clientWriteIv: Buffer;
  serverWriteIv: Buffer;
}

export interface CipherState {
  writeKey: Buffer;
  writeIv: Buffer; // 4-byte implicit part for GCM
  readKey: Buffer;
  readIv: Buffer;
  writeEpoch: number;
  writeSeq: bigint;
  readEpoch: number;
  readSeq: bigint;
}

export interface HandshakeContext {
  // Accumulated handshake messages for Finished verification
  messages: Buffer[];
  // Cookie (server side)
  cookie?: Buffer;
  // Our ephemeral ECDH key pair
  ecdhPrivateKey?: crypto.KeyObject;
  ecdhPublicKey?: crypto.KeyObject;
  // Peer's EC public key (from ServerKeyExchange or ClientKeyExchange)
  peerEcPublicKeyBytes?: Buffer;
  // Pre-master secret derived from ECDH
  preMasterSecret?: Buffer;
  // Peer certificate DER
  peerCertDer?: Buffer;
  // Selected cipher suite
  selectedCipherSuite?: number;
  // Message sequence counters
  sendMessageSeq: number;
  recvMessageSeq: number;
  // Server random (stored during ServerHello processing)
  serverRandom?: Buffer;
  // Client random (generated by client, sent to server in ClientHello)
  clientRandom?: Buffer;
  // Server requested client certificate (CertificateRequest received)
  certificateRequested?: boolean;
}
