name: demo_flutter
description: ts-rtc P2P Demo – Flutter client using flutter_webrtc
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.10.0
  web_socket_channel: ^2.4.0
  provider: ^6.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
